### PR TITLE
Adds Argent to wallets list.

### PR DESCRIPTION
**Pull request by graemeblackwood**
I added it alphabetically, but just noticed some of the other categories aren't alphabetical. So will leave you to decide where you want it.

### CODE REVIEW

**Comment by kermankohli** [comment]
I really love Argent and the craftsmanship behind it although when is it going live? Want to keep everything on the site stuff which works right now

**Comment by graemeblackwood** [comment]
@kermankohli It's already live on iOS. The Android team is working hard and it will be live soon too.

**Comment by kermankohli** [comment]
Hey sorry for the late reply! What I meant is the waitlist thing still there or can you use the app straight away?

**Comment by graemeblackwood** [comment]
Just tweaked the text to clarify there is a waiting list, though we are letting people through it steadily.

**Pull request merged**
