### PR TITLE
Add gitcoin

### PR DESCRIPTION
**Pull request by pbteja1998**
@owocki

https://deploy-preview-5--tryethereum.netlify.com/

### CODE REVIEW

**Comment by owocki** [comment]
thx; looks good!  can we fix the helmet logo to look more like it does on the presskit page?  transparency / whiteout seems wrong

http://bits.owocki.com/bc85b0b224c4/Screen%20Shot%202019-03-18%20at%2012.48.37%20PM.png

**Comment by pbteja1998** [comment]
@owocki Downloadable Logo on the press kit page does not have white/transparent font. So, what should the background color be if i use the logo in presskit page? (MilkyWay Blue color mentioned in the presskit will not work with the font color of the logo that is in press kit)

Right now I am using https://github.com/gitcoinco/creative/blob/master/Brand/Logo/SVG/GitcoinLogo_White.svg

**Comment by owocki** [comment]
@pbteja1998 thanks for the heads up.  i just fixed the logo hosted at https://github.com/gitcoinco/creative/blob/master/Brand/Logo/SVG/GitcoinLogo_White.svg  can you pls use the one i just uploaded?

**Comment by pbteja1998** [comment]
@owocki updated the logo. Does it look ok now?

**Comment by kermankohli** [comment]
Hey, can we please change the description to something more user friendly?
eg. "Earn crypto by fixing issue on open-source repos" 

Words such as "kudos" and phrases such as "learn new skills" seem too vague/aren't easy to understand.

Also, could you add a new category called "Earn" and assign Gitcoin to it? Finance isn't the right category in this case.

**Comment by owocki** [comment]
yes it does @pbteja1998

**Comment by pbteja1998** [comment]
@kermankohli Made the requested changes.

**Pull request merged**
